logLevel: debug

server:
  httpPort: 4000

projects:
  - id: main
    upstreams:
      - id: mainnet-public
        endpoint: https://eth.llamarpc.com
    networks:
      - architecture: evm
        evm:
          chainId: 1

